[capture]
x = 0
y = 0
width = 300
height = 300

[overlay]
x = 810
y = 1150
width = 300
height = 300
opacity = 1.0
click_through = true
always_on_top = true
shape = "rectangle"
show_fps = true
show_refresh_hz = true
show_capture_ms = false
show_render_ms = false

[performance]
target_fps = 300
